name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:        
    runs-on: ubuntu-latest
    env:
      app_name: calc_${{ runner.os}}

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: g++ Source.cpp functions.cpp -o ${{ env.app_name}}
        
      - name: 'Upload a Build Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            ${{ env.app_name }}**
            input.txt
          retention-days: 30
      - name: 'Send Telegram message on failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 'The checks were failed'

      - name: 'Send Telegram message on success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created push or pull request on 'master' branch:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


